name: wallet CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-22.04
    container: tiezhusun/computational-workflows:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          py.test-3